version: '3.0'

services:
  mooc.backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8030:8030"
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: codelytv-php_ddd_skeleton-mooc-mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
  rabbitmq:
    container_name: codelytv-chsarp_ddd_skeleton-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=codelytv
      - RABBITMQ_DEFAULT_PASS=c0d3ly