version: '3.0'

services:
  mssql:
    container_name: codelytv-chsarp_ddd_skeleton-mssql
    image: mcr.microsoft.com/mssql/server:2019-latest    
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes:
      - ./database/mooc.sql:/init.sql
  rabbitmq:
    container_name: codelytv-chsarp_ddd_skeleton-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=codelytv
      - RABBITMQ_DEFAULT_PASS=c0d3ly