version: '3.0'

services:
  mooc.backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8030:8030"
    depends_on:
      - mysql
  mysql:
    container_name: codelytv-csharp_ddd_skeleton-mooc-mysql
    image: mysql:8
    ports:
      - "3360:3306"
    environment:
      - MYSQL_DATABASE=csharp-ddd-skeleton
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]